version: '3.9'

networks:
  inception_network:
    name:   inception_network
    driver: bridge

volumes:
  db_volume:
    name: db_volume
    driver_opts:
      o: bind
      type: none #volume
      drive: /home/kristiyana/inception_volumes/db_volume
  wp_volume:
    name: wp_volume
    driver_opts:
      o: bind
      type: none #volume
      drive: /home/kristiyana/inception_volumes/wp_volume

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx #do i need this?
    volumes: 
      - wp_volume:/var/www/html
    ports:
      - 443:443
    depends_on:
      - wordpress
    networks:
      - inception_network
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb #do i need this?
    environment: #learn how to use the .env file
      - MYSQL_ROOT_PW
      - MYSQL_DB
    volumes:
      - db_volume:/var/lib/mysql
    # ports: #why is this not needed?
    #   - 3306:3306
    networks:
      - inception_network
    
  wordpress:
    container_name: wordpress
    build: ./recquirements/wordpress
    image:  wordpress
    volumes:
      - wp_volume:/var/www/html
    ports:
      - 9000:9000
    depends_on:
      - mariadb
    restart: always

