version: '3.9'

networks:
  inception_network:
    name:   inception_network
    driver: bridge

volumes:
  db_volume:
    name:     db_volume
    driver:   local
    driver_opts:
      o:      bind
      type:   volume
      device: /home/kristiyana/42_Inception/db
  
  wp_volume:
    name:     wp_volume
    driver:   local
    driver_opts:
      o:      bind
      type:   volume
      device: /home/krisityana/42_Inception/wordpress


services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    ports:
      - '443:443'
    volumes:
      - wp_volume:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception_network
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    ports:
      - '3306:3306'
    volumes:
      - db_volume:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception_network
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    ports:
      - '9000:9000'
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception_network
    restart: always
